import streamlit as st
import pandas as pd
import numpy as np
import time
import os
import datetime
import plotly.express as px
import plotly.graph_objects as go
import warnings
from urllib3.exceptions import NotOpenSSLWarning

from nba_api.stats.endpoints import playercareerstats, playergamelog
from nba_api.stats.static import players

warnings.filterwarnings("ignore", category=NotOpenSSLWarning)
warnings.filterwarnings("ignore", category=UserWarning, module='urllib3')

st.set_page_config(page_title="Dunkonomics | Quant Hoops", layout="wide", initial_sidebar_state="collapsed")

# Paths to the local CSV database generated by fetcher.py
DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
STANDINGS_FILE = os.path.join(DATA_DIR, "standings.csv")
TEAM_STATS_FILE = os.path.join(DATA_DIR, "team_stats.csv")
PLAYERS_FILE = os.path.join(DATA_DIR, "players.csv")
PLAYER_FOULS_FILE = os.path.join(DATA_DIR, "player_fouls.csv")
TEAM_FOULS_FILE = os.path.join(DATA_DIR, "team_fouls.csv")

# Premium CSS Styling (Dark Mode - Bloomberg/Terminal Vibe)
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;800&family=JetBrains+Mono:wght@400;700&display=swap');
    
    html, body, [class*="css"] { font-family: 'Inter', sans-serif; background-color: #0b1121; color: #e2e8f0; }
    .stApp { background-image: linear-gradient(rgba(255, 255, 255, 0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255, 255, 255, 0.03) 1px, transparent 1px); background-size: 30px 30px; }
    h1, h2, h3 { color: #f8fafc; font-weight: 800; letter-spacing: -0.5px; }
    
    .brand-container { display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 1px solid #1e293b; padding-bottom: 1rem; margin-bottom: 2rem; }
    .brand-text { font-size: 2.2rem; background: -webkit-linear-gradient(45deg, #38bdf8, #34d399); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-weight: 900; line-height: 1.1; letter-spacing: -1px; }
    .sub-brand { color: #64748b; font-size: 0.9rem; font-weight: 500; text-transform: uppercase; letter-spacing: 2px;}
    
    .status-indicator { display: flex; align-items: center; gap: 8px; font-family: 'JetBrains Mono', monospace; font-size: 0.8rem; color: #94a3b8; }
    .pulse-dot { height: 8px; width: 8px; background-color: #10b981; border-radius: 50%; display: inline-block; box-shadow: 0 0 8px #10b981; }
    
    .metric-card { background-color: #0f172a; border: 1px solid #1e293b; border-top: 3px solid #38bdf8; border-radius: 6px; padding: 20px; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.5); transition: all 0.2s ease; }
    .metric-card:hover { transform: translateY(-3px); border-top: 3px solid #34d399; box-shadow: 0 10px 25px -3px rgba(52, 211, 153, 0.2); }
    .metric-title { color: #94a3b8; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 1px; font-weight: 600; margin-bottom: 8px; }
    .metric-value { color: #f8fafc; font-size: 2.2rem; font-weight: 800; font-family: 'JetBrains Mono', monospace; line-height: 1;}
    .metric-sub { color: #10b981; font-size: 0.8rem; font-weight: 500; margin-top: 8px; font-family: 'JetBrains Mono', monospace;}
    
    .ev-card { background: linear-gradient(145deg, #064e3b, #065f46); border: 1px solid #10b981; border-radius: 8px; padding: 20px; text-align: center; margin-bottom: 10px;}
    .ev-card.negative { background: linear-gradient(145deg, #7f1d1d, #991b1b); border: 1px solid #ef4444; }
    
    .arb-card { background: linear-gradient(145deg, #1e1b4b, #312e81); border: 1px solid #8b5cf6; border-radius: 8px; padding: 20px; margin-bottom: 15px;}
    .arb-title { color: #a5b4fc; font-family: 'JetBrains Mono', monospace; font-size: 0.9rem; margin-bottom: 10px;}
    .arb-profit { color: #34d399; font-size: 1.5rem; font-weight: 800; font-family: 'JetBrains Mono', monospace; text-align: center; padding: 10px; background: rgba(0,0,0,0.3); border-radius: 4px;}
    
    .nerd-header { background: linear-gradient(90deg, #1e1b4b, #0f172a); border-left: 4px solid #8b5cf6; padding: 15px 20px; border-radius: 4px; margin-bottom: 20px;}
    .nerd-title { font-family: 'JetBrains Mono', monospace; color: #a78bfa; font-weight: 700; font-size: 1.2rem; margin: 0;}
    .nerd-formula { font-family: 'JetBrains Mono', monospace; color: #fbbf24; background: #1e293b; padding: 8px; border-radius: 4px; font-size: 0.85rem; border: 1px solid #334155;}
    
    .stDataFrame { border-radius: 6px; overflow: hidden; border: 1px solid #1e293b; }
    #MainMenu {visibility: hidden;} footer {visibility: hidden;} header {visibility: hidden;}
    
    div.row-widget.stRadio > div { flex-direction: row; gap: 10px; padding-bottom: 0px; }
    div.row-widget.stRadio > div > label { background-color: transparent; padding: 8px 16px; border-radius: 4px; border: 1px solid #1e293b; cursor: pointer; color: #94a3b8; font-weight: 500; transition: all 0.2s; }
    div.row-widget.stRadio > div > label:hover { background-color: #1e293b; color: #f8fafc; }
    div.row-widget.stRadio > div > label[data-checked="true"] { background-color: #1e293b; border-color: #38bdf8; color: #38bdf8; }
    </style>
""", unsafe_allow_html=True)

# --- STATE INIT ---
if 'parlay_legs' not in st.session_state:
    st.session_state.parlay_legs = []

import fetcher

@st.cache_resource(ttl=43200, show_spinner=False)
def trigger_fetch_cycle():
    with st.spinner("Initializing ephemeral environment & fetching fresh NBA data... This might take a minute."):
        fetcher.run_fetch_cycle()
        st.cache_data.clear()
        return True

def check_and_fetch_data():
    files_to_check = [
        STANDINGS_FILE, 
        TEAM_STATS_FILE, 
        PLAYERS_FILE,
        os.path.join(DATA_DIR, "advanced_players.csv"),
        os.path.join(DATA_DIR, "cumfat.csv"),
        PLAYER_FOULS_FILE,
        TEAM_FOULS_FILE
    ]
    
    needs_fetch = False
    for filepath in files_to_check:
        if not os.path.exists(filepath):
            needs_fetch = True
            break
        
        # Check if older than 12 hours
        if os.path.exists(filepath):
            mtime = os.path.getmtime(filepath)
            file_age_hours = (time.time() - mtime) / 3600
            if file_age_hours > 12:
                needs_fetch = True
                break
            
    if needs_fetch:
        trigger_fetch_cycle()

check_and_fetch_data()

# --- LOCAL DATA READERS ---
def get_last_updated(filepath):
    if os.path.exists(filepath):
        mtime = os.path.getmtime(filepath)
        return datetime.datetime.fromtimestamp(mtime).strftime('%Y-%m-%d %H:%M:%S EST')
    return "Pending Sync"

@st.cache_data(ttl=3600, show_spinner=False)
def load_standings():
    if os.path.exists(STANDINGS_FILE): return pd.read_csv(STANDINGS_FILE)
    return None

@st.cache_data(ttl=3600, show_spinner=False)
def load_team_stats():
    if os.path.exists(TEAM_STATS_FILE): return pd.read_csv(TEAM_STATS_FILE)
    return None

@st.cache_data(ttl=3600, show_spinner=False)
def load_players():
    if os.path.exists(PLAYERS_FILE): 
        return pd.read_csv(PLAYERS_FILE).to_dict('records')
    return players.get_active_players()

@st.cache_data(ttl=3600, show_spinner=False)
def load_advanced_players():
    advanced_path = os.path.join(DATA_DIR, 'advanced_players.csv')
    if os.path.exists(advanced_path): return pd.read_csv(advanced_path)
    return None

@st.cache_data(ttl=3600, show_spinner=False)
def load_cumfat():
    cumfat_path = os.path.join(DATA_DIR, 'cumfat.csv')
    if os.path.exists(cumfat_path): return pd.read_csv(cumfat_path)
    return None

@st.cache_data(ttl=3600, show_spinner=False)
def load_player_fouls():
    if os.path.exists(PLAYER_FOULS_FILE): return pd.read_csv(PLAYER_FOULS_FILE)
    return None

@st.cache_data(ttl=3600, show_spinner=False)
def load_team_fouls():
    if os.path.exists(TEAM_FOULS_FILE): return pd.read_csv(TEAM_FOULS_FILE)
    return None


NBA_HEADERS = {
    'Host': 'stats.nba.com',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    'Accept': 'application/json, text/plain, */*',
    'x-nba-stats-origin': 'stats',
    'x-nba-stats-token': 'true',
    'Referer': 'https://stats.nba.com/'
}

@st.cache_data(ttl=3600, show_spinner=False)
def get_player_stats(player_id):
    try:
        time.sleep(0.5)
        career = playercareerstats.PlayerCareerStats(player_id=player_id, timeout=30)
        return career.get_data_frames()[0].tail(1)
    except: return None

@st.cache_data(ttl=3600, show_spinner=False)
def get_player_full_log(player_id, season='2024-25'):
    try:
        time.sleep(0.5)
        log = playergamelog.PlayerGameLog(player_id=player_id, season=season, timeout=30)
        return log.get_data_frames()[0]
    except: return None

# --- MATH HELPER ---
def american_to_implied(odds):
    if odds > 0: return 100 / (odds + 100)
    else: return abs(odds) / (abs(odds) + 100)

def implied_to_american(prob):
    if prob <= 0 or prob >= 1: return 0
    if prob > 0.5: return int(round(prob / (1 - prob) * -100))
    else: return int(round((1 - prob) / prob * 100))

# --- ARBITRAGE MATH ---
def calculate_arbitrage(odds1, odds2):
    """Calculates if an arbitrage opportunity exists between two odds."""
    prob1 = american_to_implied(odds1)
    prob2 = american_to_implied(odds2)
    total_prob = prob1 + prob2
    
    if total_prob < 1.0:
        profit_margin = (1.0 - total_prob) * 100
        # Optimal bet sizing assuming $100 total bankroll
        bet1 = (prob1 / total_prob) * 100
        bet2 = (prob2 / total_prob) * 100
        return True, profit_margin, bet1, bet2
    return False, 0, 0, 0

# --- HEADER & NAVIGATION ---
last_sync = get_last_updated(STANDINGS_FILE)

st.markdown(f"""
    <div class='brand-container'>
        <div>
            <div class='sub-brand'>Quantitative Basketball Intelligence</div>
            <div class='brand-text'>Dunkonomics</div>
        </div>
        <div class='status-indicator'>
            <span class='pulse-dot'></span>
            DATA WAREHOUSE: ONLINE<br>
            LAST SYNC: {last_sync}
        </div>
    </div>
""", unsafe_allow_html=True)

page = st.radio("Navigation", ["League Macro", "Player Micro", "Team Advanced", "⚖️ Foul Economics", "🤓 Sports Dorks [PRO]"], horizontal=True, label_visibility="collapsed")
st.markdown("<br>", unsafe_allow_html=True)

# --- PAGE: LEAGUE MACRO ---
if page == "League Macro":
    df = load_standings()
    if df is not None and not df.empty:
        st.markdown("##### League Leaders (Win %)")
        top_teams = df.sort_values('Win %', ascending=False).head(4)
        m1, m2, m3, m4 = st.columns(4)
        metrics = [m1, m2, m3, m4]
        for i, (idx, row) in enumerate(top_teams.iterrows()):
            with metrics[i]:
                st.markdown(f"<div class='metric-card'><div class='metric-title'>{row['TeamName']}</div><div class='metric-value'>{row['Win %']:.3f}</div><div class='metric-sub'>STRK: {row['Streak']} | L10: {row['L10']}</div></div>", unsafe_allow_html=True)
        st.markdown("<br>", unsafe_allow_html=True)
        tab1, tab2 = st.tabs(["Eastern Conference", "Western Conference"])
        with tab1:
            east = df[df['Conference'] == 'East'].sort_values('Rank').drop(columns=['Conference'])
            st.dataframe(east.style.background_gradient(subset=['Diff'], cmap='RdYlGn'), use_container_width=True, hide_index=True)
        with tab2:
            west = df[df['Conference'] == 'West'].sort_values('Rank').drop(columns=['Conference'])
            st.dataframe(west.style.background_gradient(subset=['Diff'], cmap='RdYlGn'), use_container_width=True, hide_index=True)
    else:
        st.info("Warehouse syncing in progress. Data available shortly.")

# --- PAGE: PLAYER MICRO ---
elif page == "Player Micro":
    all_p = load_players()
    player_names = [p['full_name'] for p in all_p] if all_p else []
    colA, colB = st.columns([1, 3])
    with colA:
        search_query = st.selectbox("Player Search (Database)", [""] + player_names)
    if search_query:
        player_info = next((p for p in all_p if p['full_name'] == search_query), None)
        if player_info:
            pid = player_info['id']
            with st.spinner(f"Querying dynamic endpoint for {search_query}..."):
                stats_df = get_player_stats(pid)
                recent_df = get_player_full_log(pid)
            
            if stats_df is not None and not stats_df.empty:
                gp = int(stats_df['GP'].values[0])
                if gp > 0:
                    pts = round(stats_df['PTS'].values[0] / gp, 1)
                    reb = round(stats_df['REB'].values[0] / gp, 1)
                    ast = round(stats_df['AST'].values[0] / gp, 1)
                    
                    if recent_df is not None and not recent_df.empty:
                        l10 = recent_df.head(10)
                        l10_pts = round(l10['PTS'].mean(), 1)
                        pts_delta = round(l10_pts - pts, 1)
                        pts_color = "#10b981" if pts_delta >= 0 else "#ef4444"
                        pts_sign = "+" if pts_delta >= 0 else ""
                        pts_sub = f"<span style='color: {pts_color}'>{pts_sign}{pts_delta}</span> vs Season"
                    else:
                        pts_sub = "vs Season"

                    fgm, fga = stats_df['FGM'].values[0], stats_df['FGA'].values[0]
                    fg3m, fg3a = stats_df['FG3M'].values[0], stats_df['FG3A'].values[0]
                    ftm, fta = stats_df['FTM'].values[0], stats_df['FTA'].values[0]
                    ts_pct = round((stats_df['PTS'].values[0] / (2 * (fga + 0.44 * fta))) * 100, 1) if fga > 0 else 0
                    
                    st.markdown("<br>", unsafe_allow_html=True)
                    c1, c2, c3, c4 = st.columns(4)
                    c1.markdown(f"<div class='metric-card'><div class='metric-title'>Points (PPG)</div><div class='metric-value'>{pts}</div><div class='metric-sub'>{pts_sub}</div></div>", unsafe_allow_html=True)
                    c2.markdown(f"<div class='metric-card'><div class='metric-title'>Rebounds (RPG)</div><div class='metric-value'>{reb}</div><div class='metric-sub'>Total</div></div>", unsafe_allow_html=True)
                    c3.markdown(f"<div class='metric-card'><div class='metric-title'>Assists (APG)</div><div class='metric-value'>{ast}</div><div class='metric-sub'>Total</div></div>", unsafe_allow_html=True)
                    c4.markdown(f"<div class='metric-card'><div class='metric-title'>True Shooting</div><div class='metric-value'>{ts_pct}%</div><div class='metric-sub'>Efficiency Rating</div></div>", unsafe_allow_html=True)
                    
                    st.markdown("<br>", unsafe_allow_html=True)
                    col_chart, col_data = st.columns([3, 2])
                    with col_chart:
                        st.markdown("##### Scoring Volatility (Last 10)")
                        if recent_df is not None and not recent_df.empty:
                            fig = px.bar(l10[::-1], x='GAME_DATE', y='PTS', template="plotly_dark", color='PTS', color_continuous_scale='Blues')
                            fig.update_layout(plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)', margin=dict(l=0, r=0, t=0, b=0), coloraxis_showscale=False)
                            fig.add_hline(y=pts, line_dash="dot", annotation_text=f"Season Avg ({pts})", annotation_position="top right", line_color="#10b981")
                            st.plotly_chart(fig, use_container_width=True)
                    with col_data:
                        st.markdown("##### Efficiency Matrix")
                        eff_data = {"Metric": ["Field Goal %", "3-Point %", "Free Throw %", "eFG %"], "Value": [f"{round((fgm/fga)*100, 1) if fga>0 else 0}%", f"{round((fg3m/fg3a)*100, 1) if fg3a>0 else 0}%", f"{round((ftm/fta)*100, 1) if fta>0 else 0}%", f"{round(((fgm + 0.5 * fg3m) / fga)*100, 1) if fga>0 else 0}%"], "Volume": [f"{fgm}/{fga}", f"{fg3m}/{fg3a}", f"{ftm}/{fta}", "-"]}
                        st.dataframe(pd.DataFrame(eff_data), hide_index=True, use_container_width=True)
                        
                    st.markdown("##### Raw Season Totals")
                    raw_cols = ['TEAM_ABBREVIATION', 'MIN', 'FGM', 'FGA', 'FG3M', 'FG3A', 'FTM', 'FTA', 'PTS', 'REB', 'AST', 'STL', 'BLK', 'TOV']
                    st.dataframe(stats_df[raw_cols], hide_index=True, use_container_width=True)

                    st.markdown("---")
                    st.markdown("### 🏃‍♂️ Cumulative Fatigue (CumFat) Dashboard")
                    
                    cumfat_df = load_cumfat()
                    if cumfat_df is not None and not cumfat_df.empty:
                        # Match player ID
                        player_cf = cumfat_df[cumfat_df['PlayerID'] == pid]
                        if not player_cf.empty:
                            cf_score = player_cf['CumFatScore'].values[0]
                            miles = player_cf['MilesFlown'].values[0]
                            tz = player_cf['TimeZones'].values[0]
                            sched = player_cf['ScheduleContext'].values[0]
                            rest_def = player_cf['RestDeficit'].values[0]
                            workload = player_cf['RecentWorkload'].values[0]
                            
                            if cf_score < 40:
                                cf_color = "#10b981" # Green
                                cf_text = "FRESH"
                            elif cf_score <= 70:
                                cf_color = "#f59e0b" # Yellow
                                cf_text = "MODERATE"
                            else:
                                cf_color = "#ef4444" # Red
                                cf_text = "EXHAUSTED"
                                
                            st.markdown(f"<div style='text-align: center; margin-bottom: 20px;'><h1 style='color: {cf_color}; font-size: 3rem;'>{cf_score}</h1><h3 style='color: #94a3b8; font-weight: 300; margin-top: -15px;'>MASTER SCORE: {cf_text}</h3></div>", unsafe_allow_html=True)
                            
                            with st.expander("ℹ️ How is CumFat Calculated?"):
                                st.markdown("""
                                **Cumulative Fatigue (CumFat)** is our proprietary metric measuring player wear-and-tear using three core pillars:
                                - **✈️ Travel Toll (45%)**: Distance traveled and body clock disruption from crossing time zones.
                                - **📅 Schedule Density (35%)**: Rest deficits, back-to-backs, and 3-in-4 nights.
                                - **🏃 Workload (20%)**: Recent minutes played and physical expenditure on the court.
                                """)
                                
                            st.markdown("<br>", unsafe_allow_html=True)
                            cf1, cf2, cf3, cf4, cf5 = st.columns(5)
                            cf1.metric("Miles Flown", f"{miles:,}", help="Total miles flown between arenas in the last 10 days.")
                            cf2.metric("Time Zones", tz, help="Number of time zones crossed in the last 10 days. Higher values disrupt circadian rhythms.")
                            cf3.metric("Schedule Context", sched, help="Schedule density severity (e.g., B2B, 3-in-4 nights).")
                            cf4.metric("Rest Deficit", rest_def, help="Days since the player had 48 hours of rest.")
                            cf5.metric("Recent Workload", workload, help="Total minutes played by the player over the last 10 days.")
                            
                        else:
                            st.error("No recent data. Player has not logged minutes in the last 10 days to calculate Cumulative Fatigue.")
                    else:
                        st.info("CumFat Database is building. The sync loop hasn't completed yet.")
                    st.markdown("--- ")
                    st.markdown("### ⚖️ Discipline & Foul Profile")
                    player_fouls = load_player_fouls()
                    if player_fouls is not None and not player_fouls.empty:
                        pf_df = player_fouls[player_fouls['PLAYER_ID'] == pid]
                        if not pf_df.empty:
                            net_fouls = pf_df['Net_Fouls'].values[0]
                            pf = round(pf_df['PF'].values[0] / pf_df['GP'].values[0], 1) if pf_df['GP'].values[0] > 0 else 0
                            pfd = round(pf_df['PFD'].values[0] / pf_df['GP'].values[0], 1) if pf_df['GP'].values[0] > 0 else 0
                            ftr = round(pf_df['FTr'].values[0], 3)
                            
                            st.markdown("<p style='color: #94a3b8; font-size: 0.9rem; margin-top: -10px;'>A granular look at the player's ability to draw contact without fouling.</p>", unsafe_allow_html=True)
                            f1, f2, f3, f4 = st.columns(4)
                            f1.metric("Net Fouls", round(net_fouls, 1), help="Total Personal Fouls Drawn minus Personal Fouls Committed")
                            f2.metric("Personal Fouls (PG)", pf, help="Personal Fouls Committed per game")
                            f3.metric("Fouls Drawn (PG)", pfd, help="Personal Fouls Drawn per game")
                            f4.metric("Free Throw Rate (FTr)", ftr, help="Ratio of Free Throw Attempts to Field Goal Attempts (FTA / FGA)")
                        else:
                            st.info("No foul data found for this player.")
                    else:
                        st.info("Foul Profile syncing...")


# --- PAGE: TEAM ADVANCED ---

elif page == "⚖️ Foul Economics":
    st.markdown("### ⚖️ Team Foul Discipline & Free Throw Rates")
    team_fouls = load_team_fouls()
    if team_fouls is not None and not team_fouls.empty:
        st.markdown("##### Net Fouls & Free Throw Rate Differential")
        st.markdown("<p style='font-size: 0.85rem; color: #64748b; margin-top: -10px;'>Net Fouls = PFD (Fouls Drawn) - PF (Personal Fouls). High FTr = Elite at drawing contact vs settling.</p>", unsafe_allow_html=True)
        
        # Display the highly polished dataframe
        st.dataframe(
            team_fouls.style.background_gradient(subset=['Net_Fouls'], cmap='RdYlGn')
            .background_gradient(subset=['FTr'], cmap='Blues')
            .background_gradient(subset=['PF'], cmap='Reds')
            .background_gradient(subset=['PFD'], cmap='Greens')
            .format({
                'FTr': '{:.3f}', 
                'PF': '{:.1f}', 
                'PFD': '{:.1f}', 
                'FTA': '{:.1f}', 
                'FGA': '{:.1f}', 
                'Net_Fouls': '{:.1f}'
            }),
            use_container_width=True,
            hide_index=True,
            height=600
        )
    else:
        st.info("Foul Data is syncing in the background. Please check back shortly.")

# --- PAGE: TEAM ADVANCED ---
elif page == "Team Advanced":
    team_df = load_team_stats()
    if team_df is not None and not team_df.empty:
        st.markdown("##### League Efficiency Landscape")
        st.markdown("<p style='font-size: 0.85rem; color: #64748b; margin-top: -10px;'>Mapping Offensive Rating vs. Defensive Rating. Top Right = Elite Two-Way Teams.</p>", unsafe_allow_html=True)
        fig = px.scatter(
            team_df, x='OFF_RATING', y='DEF_RATING', text='TEAM_NAME', color='NET_RATING', color_continuous_scale='RdYlGn', template="plotly_dark", size='W', labels={"OFF_RATING": "Offensive Rating (Pts / 100 Poss)", "DEF_RATING": "Defensive Rating (Pts Allowed / 100 Poss)", "W": "Wins"}
        )
        fig.update_yaxes(autorange="reversed")
        fig.update_traces(textposition='top center', marker=dict(line=dict(width=1, color='#0f172a')))
        fig.update_layout(height=500, plot_bgcolor='#0b1121', paper_bgcolor='rgba(0,0,0,0)', font=dict(family="Inter", color="#94a3b8"), margin=dict(t=20))
        st.plotly_chart(fig, use_container_width=True)
        st.markdown("##### Deep Database (Sortable)")
        st.dataframe(team_df.style.background_gradient(subset=['NET_RATING'], cmap='RdYlGn').background_gradient(subset=['OFF_RATING'], cmap='Greens').background_gradient(subset=['DEF_RATING'], cmap='Reds_r').format({'OFF_RATING': '{:.1f}', 'DEF_RATING': '{:.1f}', 'NET_RATING': '{:.1f}', 'TS_PCT': '{:.3f}', 'PACE': '{:.1f}', 'AST_PCT': '{:.1f}'}), use_container_width=True, hide_index=True, height=400)
    else:
        st.info("Warehouse syncing in progress. Data available shortly.")

# --- PAGE: SPORTS DORKS ---
elif page == "🤓 Sports Dorks [PRO]":
    st.markdown("<div class='nerd-header'><h3 class='nerd-title'>SPORTS DORKS: THE LABORATORY</h3><p style='color: #94a3b8; font-size: 0.9rem; margin-top: 5px;'>Welcome to the basement. Here we break down traditional counting stats into our proprietary composite metrics.</p></div>", unsafe_allow_html=True)
    st.markdown("### The Proprietary Metrics")
    col1, col2 = st.columns(2)
    with col1:
        st.markdown("#### 1. DUNK Score (Dunkonomics Universal Net Kinetcs)")
        st.markdown("<div class='nerd-formula'>DUNK = (TS% * 0.4) + (AST% * 0.3) + (USG% * 0.2) + (STL% + BLK%) - (TOV% * 1.5)</div>", unsafe_allow_html=True)
        st.markdown("<p style='color:#cbd5e1; font-size:0.85rem; margin-top:10px;'><b>What it measures:</b> The ultimate offensive engine metric. Heavily penalizes turnovers, rewards highly efficient hub players.</p>", unsafe_allow_html=True)
    with col2:
        st.markdown("#### 2. Gravity Index (GRAV)")
        st.markdown("<div class='nerd-formula'>GRAV = (3PA / 100 Poss) * (3P%)^2 * (Drive_Kick_Rate)</div>", unsafe_allow_html=True)
        st.markdown("<p style='color:#cbd5e1; font-size:0.85rem; margin-top:10px;'><b>What it measures:</b> How much defense a player sucks into their orbit simply by standing on the floor.</p>", unsafe_allow_html=True)

    st.markdown("---")
    st.markdown("### Interactive DUNK Score Explorer")
    
    import plotly.express as px
    import os
    
    df_advanced = load_advanced_players()
    if df_advanced is not None and not df_advanced.empty:
        # Display the highly polished dataframe
        st.dataframe(
            df_advanced.style.background_gradient(subset=['DUNK_SCORE'], cmap='Purples')
            .background_gradient(subset=['TS_PCT'], cmap='Greens')
            .format({
                'TS_PCT': '{:.3f}', 
                'AST_PCT': '{:.3f}', 
                'USG_PCT': '{:.3f}', 
                'PIE': '{:.3f}', 
                'TM_TOV_PCT': '{:.3f}', 
                'DUNK_SCORE': '{:.2f}'
            }),
            use_container_width=True,
            hide_index=True,
            height=400
        )
        
        st.markdown("### Offensive Efficiency: Usage vs True Shooting")
        
        # Filter for players with decent minutes to avoid noise
        df_plot = df_advanced[df_advanced['MIN'] > 15].copy()
        
        fig = px.scatter(
            df_plot,
            x='TS_PCT',
            y='USG_PCT',
            hover_name='PLAYER_NAME',
            hover_data=['TEAM_ABBREVIATION', 'DUNK_SCORE'],
            color='DUNK_SCORE',
            color_continuous_scale='Purples',
            title='Usage Rate vs True Shooting Percentage (Min > 15 MPG)',
            labels={'TS_PCT': 'True Shooting %', 'USG_PCT': 'Usage Rate %'}
        )
        fig.update_layout(template='plotly_dark')
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("Advanced player data is syncing in the background. Please check back shortly.")


st.markdown("---")
st.markdown("<p style='text-align: center; color: #475569; font-size: 0.75rem; font-family: JetBrains Mono;'>SYSTEM: DUNKONOMICS OS v1.0.1 // DATA: STATS.NBA.COM // STATUS: OPERATIONAL</p>", unsafe_allow_html=True)